packages:
  - apps/*
  - packages/*
allowBuilds:
  cpu-features: true
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pty: true
  ssh2: true
minimumReleaseAgeExclude:
  - '@types/node@26.6.2'
  - electron@44.4.3
